[project]
name = "hackernewsupvotepredictor"
version = "0.0.1"
description = "MLX week one - Hacker News Upvote Predictor"
authors = [
    {name = "Helen Zhou"}
]
license = {text = "MIT License"}
readme = "README.md"
requires-python = "=3.9.6"
dependencies = [
    "python-dotenv (>=1.1.0,<2.0.0)",
    "psycopg2-binary (>=2.9.10,<3.0.0)",
]

[tool.poetry]
name = "hackernewsupvotepredictor"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
